### ISSUE TITLE
ISSUE

### ISSUE THREAD

**Issue by moiling** [acemurder/BIHu#1]
总体来看还是不错的，注意到了下拉换页的处理还是不错的，相对一部分孩子们

- 1.一进去那个左右顶格的逼字……确实把我吓到了，不要那么大！我们要边距！
- 2.登录和注册按钮弹出来的其实是一个dialog呢，而且那白色的字……我确实看不太清
- 3.头像没显示呢，没事没事

**Comment by acemurder** [comment]
@moiling 谢谢学姐，我还在改🙈🙈🙈，刚把头像储存撸完，换了头像的显示，都能显示了，断网了，明天push上来。后面再调整ui😀😀😀
